const actions = {
  CREATE_PROFILE: 'profile/CREATE_PROFILE',
  SET_STATE: 'profile/SET_STATE',
  EDIT_PROFILE: 'profile/EDIT_PROFILE',
  CREATE_POST: 'profile/CREATE_POST',
  EDIT_POST: 'profile/EDIT_POST',
  EDIT_EDUCATION: 'profile/EDIT_EDUCATION',
  DELETE_EDUCATION: 'profile/DELETE_EDUCATION',
  EDIT_ARTICLES: 'profile/EDIT_ARTICLES',
  DELETE_ARTICLES: 'profile/DELETE_ARTICLES',
  EDIT_EXPERIENCE: 'profile/EDIT_EXPERIENCE',
  DELETE_EXPERIENCE: 'profile/DELETE_EXPERIENCE',
  EDIT_LEADERSHIP: 'profile/EDIT_LEADERSHIP',
  DELETE_LEADERSHIP: 'profile/DELETE_LEADERSHIP',
  EDIT_BRAGS: 'profile/EDIT_BRAGS',
  DELETE_BRAGS: 'profile/DELETE_BRAGS',
  SELECT_THEME: 'profile/SELECT_THEME',
  LOAD_CURRENT_PROFILE: 'profile/LOAD_CURRENT_PROFILE'
}

export default actions
